version: '3'
services:
  dn-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dn-env
    privileged: true
    shm_size: 512g
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ${PWD}:${PWD}
    ports:
      - 19555:8888
    working_dir: ${PWD}
    stdin_open: true
    tty: true

